### ISSUE TITLE
Accepting stdin as input

### ISSUE THREAD

**Issue by Neato-Nick** [mpdunne/alan#2]
Hi,

I love this tool! Easy to use and install, output has pretty and useful colors

Would it be possible to allow stdin as input? Bioinformatics tools love to work with streams, would be really nice if I could look at stream output with alan instead of the far-inferior less

I wanted to post a minimal example to demonstrate, sorry for the useless use of cat

```
printf ">test\nMVVLKR" > test_seq.pep
cat test_seq.pep | alan -
```

**Comment by ghost** [comment]
Hi Nick - I've updated this now to allow piped input!

**Comment by Neato-Nick** [comment]
Just cloned the repo, it totally does work using | or < for stdin! Thank you so much!
